### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by brenolf** [DoctorMcKay/node-steamstuff#1]
I'm trying a very simple example to connect on Steam:

``` js
var Steam = require('steam');
var SteamStuff = require('steamstuff');

var steamClient = new Steam.SteamClient();

// var steamUser = new Steam.SteamUser(steamClient);

SteamStuff(Steam, steamClient);

// steamClient.connect();

steamClient.logOn({
  account_name: 'brenolf',
  password: '!1208Breno'
});
```

But I get the title's error. This is because using `node-steam ^1.1.0` that function is available on SteamUser and not SteamClient class.

**Comment by DoctorMcKay** [comment]
SteamStuff is available for node-steam 0.6.x and earlier only.

You may want to check out [node-steam-user](https://github.com/DoctorMcKay/node-steam-user) which does something similar for 1.0.
